version: '2'
exclude_patterns:
  - '.next/'
  - 'node_modules/'

checks:
  method-lines:
    config:
      threshold: 50

---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
