name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    needs: [test]
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        node: ['12']
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn test
  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install -g yarn
      - run: yarn install
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: f95b54530c25afc2381ebcf0ffbf3477b7690d6dd4e3d65b1931ed5dc287ca47
        with:
          coverageCommand: yarn test:coverage
          coverageLocation: ${{github.workspace}}/coverage/lcov.info:lcov
